name: wl_platform
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^10.0.0
  dio: ^5.9.0
  easy_localization: ^3.0.8
  shared_preferences: ^2.5.4
  isar_community: ^3.3.0
  isar_community_flutter_libs: ^3.3.0
  mobile_device_identifier: ^0.0.3
  device_info_plus: ^12.3.0
  uuid: ^4.5.2
  appmetrica_plugin: ^3.4.0
  get_storage: ^2.1.1
  get_it: ^9.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_community_generator: ^3.3.0
  build_runner: ^2.7.1


  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/core/localization/translations/core/



